version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dd_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "56000:56000"

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:56000/api
    depends_on:
      - backend
    ports:
      - "54287:54287"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "54287"]

volumes:
  db_data:
